spring:  
  application:
    name: account-service
  cloud:
    consul:
      host: localhost
      port: 8500
  config:
    import: optional:consul:localhost:8500
  output.ansi.enabled: ALWAYS

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

---
spring:
  cloud:
    consul:
      discovery:
        instanceZone: zone1
  config:
    activate:
      on-profile: zone1
---
spring:
  cloud:
    consul:
      discovery:
        instanceZone: zone2
  config:
    activate:
      on-profile: zone2